
POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
    "username":"vikash308",
    "password":"12345",
    "email": "vikas@gmail.com",
    "name":"vikash"
}

###

Post http://localhost:9090/login  HTTP/1.1
Content-Type: application/json

{
    "email": "vikas@gmail.com",
    "password": "12345"
}

###
Post http://localhost:9090/update_profile_picture  HTTP/1.1
Content-Type: application/json

{
    "profile_picture"
    "token":
}

###

GET http://localhost:9090/get_user_and_profile 
Content-Type: application/json

{
    "token": "322a90edad8b2f4fa507e42326426ec0946efe9a06fd6868f2d269b3ff25eab8"
}

###

Post http://localhost:9090/update_profile_data  HTTP/1.1
Content-Type: application/json

{
    "token": "2683636904fe69da838c5e0e3318f078b3da410200fd0b0750db36ef032d3592",
    "bio": "",
    "currentPost": "CTO",
    "pastWork" :[
        {
            "company": "microsoft",
            "position": "CTO",
            "year": "2+"
        }
    ],
    "education" : [
        {
            "school": "IIT",
            "degree" : "B. Tech",
            "fileOfStudy": "2015-2019"
        }
    ]
}


###

GET http://localhost:9090/user/get_all_user_profile
